//
// Created by George on 7/7/2024.
//

#ifndef PEOPLECOUNTER_LIBRARY_PEOPLECOUNTER_CONFIG_H
#define PEOPLECOUNTER_LIBRARY_PEOPLECOUNTER_CONFIG_H

enum MODE{
    ACTIVE_LOW,
    ACTIVE_HIGH
};

#endif //PEOPLECOUNTER_LIBRARY_PEOPLECOUNTER_CONFIG_H
